### ISSUE TITLE
Can onedrive-fuse be installed on ubuntu?

### ISSUE THREAD

**Issue by zhmlcg** [oxalica/onedrive-fuse#2]
Can `onedrive-fuse` be installed on ubuntu?

**Comment by oxalica** [comment]
Please follow [the README](https://github.com/oxalica/onedrive-fuse#usage) for installation.
For Ubuntu, you need to install `libssl-dev`, `libfuse-dev` and `cargo` via `apt` first, and then `cargo install onedrive-fuse`. It will automatically compile and install.
