### ISSUE TITLE
can't write despite login in with read-write permissions

### ISSUE THREAD

**Issue by kurokirasama** [oxalica/onedrive-fuse#4]
I logged in with:
```
onedrive-fuse login --read-write --client-id xxxx
```
and mount with 
```
onedrive-fuse mount ~/onedrive
```
However, if I try to remove a file, I get:
```
Could not delete because: Read-only file system (os error 30)
```
Am I doing or did I did something wrong?

**Comment by oxalica** [comment]
Sorry for the late response.

[The default mount options](https://github.com/oxalica/onedrive-fuse/blob/8c039e66e1a065844f56ce0ec830dcb9613c37eb/config.default.toml#L2-L3) are set to readonly.
You need to invoke `onedrive-fuse mount ~/onedrive -o permission.readonly=false`, which is mentioned in README.

N.B. The `login` command requests for readonly token or readwrite token depending to the argument (guarded by Microsoft). Readonly token is only allowed to mount readonly, while readwrite token is allowed to mount readonly or readwrite (guarded by this program).
