### ISSUE TITLE
Login fails when other query parameters are present in url

### ISSUE THREAD

**Issue by fallen90** [oxalica/onedrive-fuse#8]
I've encountered a problem logging in after copy-pasting the full url to the terminal.

```
https://login.microsoftonline.com/common/oauth2/nativeclient?code=xxxxx_xxxx_xxxxx_xxx&session_state=xxxxx-xxxxx-xxxx-xxxx-xxxxxxx
````

Here's the error
```
Logining...
Error: OAuth2 error with 400 Bad Request: (invalid_grant) AADSTS9002313: Invalid request. Request is malformed or invalid.
Trace ID: d14cecf5-20c1-4181-ba87-9913ca977b00
Correlation ID: 363a28fe-1fe3-4700-90db-b3a7b36ae9c8
Timestamp: 2023-03-07 23:00:06Z
```

So I just redid the login process but instead of the full url, I've removed all query params except `code`

**Comment by oxalica** [comment]
> So I just redid the login process but instead of the full url, I've removed all query params except `code`

I assume it works after you remove the extra query params.

We should only extract one UUID length after `code=` here:
https://github.com/oxalica/onedrive-fuse/blob/eff08d0487a8dc569a2947c46daf8395bc246035/src/main.rs#L92-L96

Maybe a better way is to just start a mini server on localhost and let the browser redirects to `http://localhost:<random-port>/onedrive-fuse`. So users don't need to copy-and-paste manually.
